name: risczero toolchain install
description: Install risczero toolchain

inputs:
  risczero-version:
    description: 'Version of the RISC Zero zkvm to install'
    required: false
    default: '1.2.0-rc.2'
    type: string

  toolchain-version:
    description: 'Version of the RISC Zero toolchains to install'
    required: false
    default: 'r0.1.81.0'
    type: string

runs:
  using: composite
  steps:
    - name: install rust
      uses: risc0/risc0/.github/actions/rustup@release-1.1

    - uses: baptiste0928/cargo-install@904927dbe77864e0f2281519fe9d5bd097a220b3
      with:
        crate: cargo-binstall
        version: '=1.10.8'
        locked: true

    - run: cargo binstall -y --force cargo-risczero@${{ inputs.risczero-version }}
      shell: bash

    - run: cargo risczero install --version "${{ inputs.toolchain-version }}"
      shell: bash

    - name: test risczero
      shell: bash
      run: cargo risczero --version