CREATE TABLE IF NOT EXISTS metric_state (
    id BOOLEAN PRIMARY KEY DEFAULT TRUE,
    last_run BIGINT NOT NULL DEFAULT 0
);

INSERT INTO metric_state (id) VALUES (TRUE)
  ON CONFLICT (id) DO NOTHING;
