// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant ECHO_ID = bytes32(0xf8fc927bc07a3e6881ed4a58a4c94fc1da0f109fed297d01498dc36784d4df31);
    bytes32 public constant IDENTITY_ID = bytes32(0x933b39fef804251b425c68203908150fd15f051382cdd63afe10bd30f06ee7b5);
}
